# Generated by Django 5.0.6 on 2026-06-19 14:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Mantenimiento preventivo'), ('CORRECTIVO', 'Mantenimiento correctivo'), ('INSTALACION', 'Instalación'), ('RETIRO', 'Retiro de equipo'), ('REVISION', 'Revisión general')], max_length=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada')], default='PENDIENTE', max_length=15)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('equipo_id', models.PositiveIntegerField(help_text='ID del equipo en ms-equipos')),
                ('equipo_nombre', models.CharField(max_length=200)),
                ('equipo_serial', models.CharField(max_length=100)),
                ('cliente_id', models.PositiveIntegerField(blank=True, null=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción del problema o trabajo a realizar')),
                ('diagnostico', models.TextField(blank=True, help_text='Diagnóstico del técnico')),
                ('solucion_aplicada', models.TextField(blank=True)),
                ('fecha_programada', models.DateField(help_text='Fecha en que se planea realizar el trabajo')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('contador_al_servicio', models.PositiveIntegerField(blank=True, help_text='Valor del contador de ciclos cuando se realizó el servicio', null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas_internas', models.TextField(blank=True)),
                ('creado_por', models.CharField(blank=True, max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'ordering': ['-fecha_programada', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('INTERNO', 'Técnico interno'), ('EXTERNO', 'Proveedor externo')], default='INTERNO', max_length=10)),
                ('empresa', models.CharField(blank=True, help_text='Solo para técnicos externos', max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('especialidad', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PiezaReemplazada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pieza', models.CharField(help_text='Ej: Fusor, Rodillo de transferencia, Banda OPC', max_length=200)),
                ('numero_parte', models.CharField(blank=True, help_text='Código o número de parte del fabricante', max_length=100)),
                ('marca_pieza', models.CharField(blank=True, help_text='Original, Compatible, Remanufacturada', max_length=100)),
                ('cantidad', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='mantenimiento.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Pieza reemplazada',
                'verbose_name_plural': 'Piezas reemplazadas',
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='mantenimiento.tecnico'),
        ),
        migrations.CreateModel(
            name='MantenimientoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_id', models.PositiveIntegerField()),
                ('equipo_nombre', models.CharField(max_length=200)),
                ('equipo_serial', models.CharField(max_length=100)),
                ('cliente_id', models.PositiveIntegerField(blank=True, null=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('nombre', models.CharField(help_text='Ej: Mantenimiento preventivo mensual', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('frecuencia_meses', models.PositiveSmallIntegerField(default=1, help_text='Cada cuántos meses se realiza este mantenimiento', validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=12)),
                ('fecha_inicio_programa', models.DateField(help_text='Desde cuándo aplica este programa')),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('dias_anticipacion', models.PositiveSmallIntegerField(default=7, help_text='Días antes de la fecha programada para crear la orden de trabajo')),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_programados', to='mantenimiento.tecnico')),
            ],
            options={
                'verbose_name': 'Mantenimiento programado',
                'verbose_name_plural': 'Mantenimientos programados',
                'ordering': ['fecha_proximo_mantenimiento'],
            },
        ),
    ]
